// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxdvbtpralnbkntrgmqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZHZidHByYWxuYmtudHJnbXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTU0MjQsImV4cCI6MjA2NjUzMTQyNH0.2awV7sLi0PyIlljeDV4ZcyjDSm8XAygpFKpGYGYO7bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);